<template>
  <div class="nono-rich-editor" :class="{ 'nono-rich-editor--fill': fill, 'is-disabled': disabled, 'is-readonly': readonly }">
    <div class="nono-rich-editor__shell" :class="{ 'is-focused': focused }">
      <div v-if="editor" class="nono-rich-editor__toolbar" role="toolbar" :aria-label="tr('Formatting tools', '格式工具')">
        <div class="nono-rich-editor__group">
          <button type="button" class="nono-rich-editor__button" :disabled="!editable || sourceMode || !canUndo" :title="tr('Undo', '撤销')" @click="command('undo')">↶ <span>{{ tr('Undo', '撤销') }}</span></button>
          <button type="button" class="nono-rich-editor__button" :disabled="!editable || sourceMode || !canRedo" :title="tr('Redo', '重做')" @click="command('redo')">↷ <span>{{ tr('Redo', '重做') }}</span></button>
        </div>
        <div class="nono-rich-editor__group">
          <select class="nono-rich-editor__select" :disabled="!editable" :aria-label="tr('Text style', '文字样式')" :value="activeBlock" @change="setBlock">
            <option value="paragraph">{{ tr('Paragraph', '正文') }}</option><option value="heading-2">{{ tr('Heading 2', '标题 2') }}</option><option value="heading-3">{{ tr('Heading 3', '标题 3') }}</option><option value="heading-4">{{ tr('Heading 4', '标题 4') }}</option>
          </select>
        </div>
        <div class="nono-rich-editor__group">
          <button type="button" class="nono-rich-editor__icon is-bold" :disabled="!editable" :class="{ 'is-active': active('bold') }" :title="tr('Bold', '粗体')" @click="toggleMark('bold')">B</button>
          <button type="button" class="nono-rich-editor__icon is-italic" :disabled="!editable" :class="{ 'is-active': active('italic') }" :title="tr('Italic', '斜体')" @click="toggleMark('italic')">I</button>
          <button type="button" class="nono-rich-editor__icon is-strike" :disabled="!editable" :class="{ 'is-active': active('strike') }" :title="tr('Strikethrough', '删除线')" @click="toggleMark('strike')">S</button>
        </div>
        <div class="nono-rich-editor__group nono-rich-editor__group--menu">
          <details ref="tableMenu" class="nono-rich-editor__table-menu">
            <summary class="nono-rich-editor__button" :class="{ 'is-active': active('table') }">▦ <span>{{ tr('Table', '表格') }}</span>⌄</summary>
            <div class="nono-rich-editor__table-panel" role="menu" :aria-label="tr('Table tools', '表格工具')">
              <button type="button" class="nono-rich-editor__table-action is-wide" :disabled="!editable || (!sourceMode && active('table'))" @click="insertTable">▦ {{ tr('Insert 3 × 3 table', '插入 3 × 3 表格') }}</button>
              <div class="nono-rich-editor__divider"></div>
              <div class="nono-rich-editor__table-grid">
                <button type="button" class="nono-rich-editor__table-action" :disabled="!editable || sourceMode || !active('table')" @click="tableCommand('addRowAfter')">＋ {{ tr('Add row', '增加行') }}</button><button type="button" class="nono-rich-editor__table-action" :disabled="!editable || sourceMode || !active('table')" @click="tableCommand('deleteRow')">－ {{ tr('Delete row', '删除行') }}</button>
                <button type="button" class="nono-rich-editor__table-action" :disabled="!editable || sourceMode || !active('table')" @click="tableCommand('addColumnAfter')">＋ {{ tr('Add column', '增加列') }}</button><button type="button" class="nono-rich-editor__table-action" :disabled="!editable || sourceMode || !active('table')" @click="tableCommand('deleteColumn')">－ {{ tr('Delete column', '删除列') }}</button>
              </div>
              <button type="button" class="nono-rich-editor__table-action is-wide is-danger" :disabled="!editable || sourceMode || !active('table')" @click="tableCommand('deleteTable')">× {{ tr('Delete table', '删除整个表格') }}</button>
            </div>
          </details>
        </div>
        <div class="nono-rich-editor__group">
          <button type="button" class="nono-rich-editor__icon" :disabled="!editable" :class="{ 'is-active': active('bulletList') }" :title="tr('Bullet list', '项目列表')" @click="command('toggleBulletList')">•</button><button type="button" class="nono-rich-editor__icon is-small" :disabled="!editable" :class="{ 'is-active': active('orderedList') }" :title="tr('Numbered list', '编号列表')" @click="command('toggleOrderedList')">1.</button><button type="button" class="nono-rich-editor__icon" :disabled="!editable" :class="{ 'is-active': active('blockquote') }" :title="tr('Quote', '引用')" @click="command('toggleBlockquote')">“</button><button type="button" class="nono-rich-editor__icon is-code" :disabled="!editable" :class="{ 'is-active': active('code') }" :title="tr('Inline code', '行内代码')" @click="toggleMark('code')">&lt;/&gt;</button>
        </div>
        <div class="nono-rich-editor__group nono-rich-editor__group--menu">
          <button type="button" class="nono-rich-editor__button" :disabled="!editable" :class="{ 'is-active': active('link') || linkOpen }" @click="editLink">↗ <span>{{ tr('Link', '链接') }}</span></button>
          <div v-if="linkOpen" ref="linkPanel" class="nono-rich-editor__link-panel" @keydown.esc="closeLink">
            <label><span>{{ tr('Link URL', '链接地址') }}</span><input ref="linkInput" v-model="linkDraft" :aria-label="tr('Link URL', '链接地址')" type="url" placeholder="https://" @keydown.enter.prevent="applyLink"></label>
            <div><button type="button" @click="applyLink">{{ tr('Apply', '应用') }}</button><button type="button" class="is-danger" @click="removeLink">{{ tr('Remove', '移除') }}</button></div>
          </div>
          <label v-if="uploadImages" class="nono-rich-editor__button nono-rich-editor__upload" :class="{ 'is-disabled': uploading || !editable }">↑ <span>{{ uploading ? uploadButtonText : tr('Upload', '上传') }}</span><input type="file" :accept="imageAccept" :disabled="uploading || !editable" multiple @change="handleUpload"></label>
          <button v-if="enableGallery" type="button" class="nono-rich-editor__button" :disabled="!editable" :title="tr('Gallery', '图册')" @click="openGallery"><svg class="nono-rich-editor__gallery-icon" viewBox="0 0 20 20" aria-hidden="true"><rect x="2.5" y="3" width="6" height="6" rx="1"></rect><rect x="11.5" y="3" width="6" height="6" rx="1"></rect><rect x="2.5" y="11" width="6" height="6" rx="1"></rect><rect x="11.5" y="11" width="6" height="6" rx="1"></rect></svg><span>{{ tr('Gallery', '图册') }}</span></button>
        </div>
        <div class="nono-rich-editor__group"><button type="button" class="nono-rich-editor__button" :disabled="disabled" :class="{ 'is-active': sourceMode }" :aria-pressed="sourceMode" @click="toggleSource">MD <span>{{ sourceMode ? tr('Visual', '可视化') : tr('Source', '源码') }}</span></button></div>
        <slot name="toolbar-end"></slot>
      </div>
      <div v-if="protectedMarkdownFeatures.length" class="nono-rich-editor__notice" role="status">{{ sourceProtectionNotice }}</div>
      <div v-if="uploadStatus" class="nono-rich-editor__upload-status"><div><strong>{{ uploadStatus.name }}</strong><span class="nono-rich-editor__upload-summary"><span :class="`is-${uploadStatus.status}`">{{ uploadStatusText }}</span><button v-if="uploading && uploadStatus.status === 'uploading'" type="button" :title="tr('Cancel upload', '取消上传')" @click="cancelUpload">{{ tr('Cancel', '取消') }}</button></span></div><div class="nono-rich-editor__progress"><i :class="`is-${uploadStatus.status}`" :style="{ width: `${uploadStatus.progress}%` }"></i></div><p v-if="uploadStatus.error">{{ uploadStatus.error }}</p></div>
      <div v-if="selectedImage && editable && !sourceMode" class="nono-rich-editor__image-details">
        <label>{{ tr('Image description', '图片说明') }} <input v-model="imageAltDraft" :aria-label="tr('Image description', '图片说明')" @keydown.enter.prevent="applyImageDescription"></label>
        <button type="button" @click="applyImageDescription">{{ tr('Apply', '应用') }}</button>
      </div>
      <div v-if="editorError" class="nono-rich-editor__fallback"><textarea :value="modelValue" :disabled="disabled" :readonly="readonly" :placeholder="placeholder" @input="emit('update:modelValue', $event.target.value)"></textarea><p>{{ editorError }}</p></div>
      <textarea v-else-if="sourceMode" ref="sourceInput" :value="sourceValue" :disabled="disabled" :readonly="readonly" :placeholder="placeholder" class="nono-rich-editor__source" :style="{ '--nono-editor-min-height': minHeight }" spellcheck="false" @input="publish($event.target.value)" @paste="handleSourcePaste" @focus="focused = true" @blur="focused = false"></textarea>
      <EditorContent v-else :editor="editor" class="nono-rich-editor__content" :style="{ '--nono-editor-min-height': minHeight }" />
      <div v-if="editor && !editorError" class="nono-rich-editor__footer"><span>{{ tr('{count} characters', '{count} 个字符', { count: characterCount }) }}</span><span class="nono-rich-editor__footer-meta"><slot name="footer-status"></slot><span>{{ sourceMode ? tr('Markdown source', 'Markdown 源码') : tr('Markdown compatible', '兼容 Markdown') }}</span></span></div>
    </div>
    <p v-if="help" class="nono-rich-editor__help">{{ help }}</p>
    <div v-if="galleryOpen" class="nono-rich-editor__gallery-overlay" @keydown.esc.stop.prevent="closeGallery">
      <section role="dialog" aria-modal="true" :aria-label="tr('Insert gallery', '插入图册')" class="nono-rich-editor__gallery-dialog">
        <h2>{{ tr('Insert gallery', '插入图册') }}</h2>
        <fieldset><legend>{{ tr('Images', '图片数量') }}</legend><label v-for="count in [2, 3, 4]" :key="count"><input type="radio" name="nono-gallery-columns" :value="count" :checked="galleryItems.length === count" @change="setGalleryColumns(count)">{{ tr('{count} images', '{count} 张图片', { count }) }}</label></fieldset>
        <div class="nono-rich-editor__gallery-items">
          <div v-for="(item, index) in galleryItems" :key="item.id" class="nono-rich-editor__gallery-item">
            <div class="nono-rich-editor__gallery-preview"><img v-if="item.url" :src="item.url" :alt="item.alt || item.caption"><span v-else>{{ tr('No image selected', '尚未选择图片') }}</span></div>
            <div class="nono-rich-editor__gallery-item-actions">
              <button type="button" @click="pickGalleryImage(item.id)">{{ tr('Choose image', '选择图片') }}</button>
              <button v-if="uploadImages" type="button" :disabled="galleryUploading" @click="openGalleryUpload(item.id)">{{ tr('Upload image', '上传图片') }}</button>
              <button type="button" :disabled="index === 0" :aria-label="tr('Move left', '左移')" @click="moveGalleryItem(index, -1)">←</button>
              <button type="button" :disabled="index === galleryItems.length - 1" :aria-label="tr('Move right', '右移')" @click="moveGalleryItem(index, 1)">→</button>
              <button type="button" :disabled="galleryItems.length <= 2" :aria-label="tr('Remove image', '删除图片')" @click="removeGalleryItem(index)">×</button>
            </div>
            <input v-model="item.caption" :aria-label="tr('Caption for image {count}', '第 {count} 张图片标注', { count: index + 1 })" :placeholder="tr('Image caption (optional)', '输入单图文字说明（选填）')">
            <input v-model="item.alt" :aria-label="tr('Description for image {count}', '第 {count} 张图片替代文字', { count: index + 1 })" :placeholder="tr('Image description (optional)', '图片替代文字（选填）')">
          </div>
        </div>
        <input ref="galleryFileInput" class="nono-rich-editor__gallery-file" type="file" :accept="imageAccept" @change="handleGalleryUpload">
        <div v-if="galleryPickerId" class="nono-rich-editor__gallery-picker"><slot name="gallery-picker" :onSelect="selectGalleryImage" :close="closeGalleryPicker"></slot></div>
        <p v-if="galleryError" role="alert" class="nono-rich-editor__gallery-error">{{ galleryError }}</p>
        <div class="nono-rich-editor__gallery-footer"><button type="button" @click="closeGallery">{{ tr('Cancel', '取消') }}</button><button type="button" :disabled="!canInsertGallery || galleryUploading" @click="insertGallery">{{ tr('Insert into document', '插入到正文') }}</button></div>
      </section>
    </div>
  </div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue';
import { Editor, EditorContent } from '@tiptap/vue-3';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import { TableKit } from '@tiptap/extension-table';
import { Markdown } from '@tiptap/markdown';
import { NodeSelection } from '@tiptap/pm/state';
import { Placeholder } from '@tiptap/extensions';
import { findRemoteImageReferences, findUnsupportedMarkdown, importRemoteImagesFromContent, requiresSourceMode } from '@nonoim/editor-core';
import { buildGalleryMarkdown } from './gallery.js';

const DEFAULT_IMAGE_ACCEPT = 'image/jpeg,image/png,image/webp,image/gif,image/svg+xml';
const props = defineProps({ modelValue: { type: String, default: '' }, placeholder: { type: String, default: '' }, rows: { type: Number, default: 10 }, help: { type: String, default: '' }, fill: { type: Boolean, default: false }, disabled: { type: Boolean, default: false }, readonly: { type: Boolean, default: false }, autofocus: { type: Boolean, default: false }, allowBase64Images: { type: Boolean, default: false }, locale: { type: String, default: 'en' }, uploadImages: { type: Function, default: null }, importRemoteImages: { type: Function, default: null }, imageAccept: { type: String, default: DEFAULT_IMAGE_ACCEPT }, maxImageSize: { type: Number, default: 10 * 1024 * 1024 }, autoSourceMode: { type: Boolean, default: false }, enableGallery: { type: Boolean, default: true } });
const emit = defineEmits(['update:modelValue', 'warning', 'upload-complete', 'upload-error', 'upload-cancel', 'remote-image-import-start', 'remote-image-import-complete', 'remote-image-import-error', 'gallery-pick-image']);
const tr = (en, zh, vars) => { let text = /^zh(?:-|$)/i.test(props.locale) ? (zh || en) : en; return vars ? text.replace(/\{(\w+)\}/g, (_m, key) => vars[key] == null ? '' : String(vars[key])) : text; };
const editor = shallowRef(null); const editorError = ref(''); const focused = ref(false); const tick = ref(0); const lastValue = ref(null); const sourceMode = ref(false); const sourceValue = ref(props.modelValue || ''); const sourceInput = ref(null); const sourceLinkSelection = ref(null); const tableMenu = ref(null); const uploadStatus = ref(null); const uploadController = shallowRef(null); const remoteImportController = shallowRef(null); const uploadingFiles = shallowRef([]); const linkOpen = ref(false); const linkDraft = ref(''); const linkPanel = ref(null); const linkInput = ref(null);
const galleryOpen = ref(false); const galleryItems = ref([]); const galleryPickerId = ref(null); const galleryFileInput = ref(null); const galleryError = ref(''); const galleryUploading = ref(false); const galleryUploadTarget = ref(null); const gallerySequence = ref(0); const imageAltDraft = ref('');
const editable = computed(() => !props.disabled && !props.readonly); const uploading = computed(() => Boolean(uploadController.value)); const protectedMarkdownFeatures = computed(() => sourceMode.value ? findUnsupportedMarkdown(sourceValue.value) : []); const minHeight = computed(() => props.fill ? '640px' : `${Math.max(420, props.rows * 32)}px`);
const selectedImage = computed(() => { tick.value; if (sourceMode.value || !editor.value?.isActive('image')) return null; return editor.value.getAttributes('image'); });
const canInsertGallery = computed(() => galleryItems.value.length >= 2 && galleryItems.value.length <= 4 && galleryItems.value.every((item) => item.url));
const sourceProtectionNotice = computed(() => { const names = { 'task-list': tr('task lists', '任务列表'), frontmatter: 'frontmatter', footnote: tr('footnotes', '脚注'), 'raw-html': 'HTML' }; const features = protectedMarkdownFeatures.value.map((feature) => names[feature] || feature).join(', '); return tr('This content uses {features}. It stays in source mode to prevent formatting loss.', '此内容使用了 {features}。为避免格式丢失，已保留在源码模式。', { features }); });
const characterCount = computed(() => { tick.value; return sourceMode.value ? sourceValue.value.length : (editor.value?.getText()?.length || 0); }); const canUndo = computed(() => { tick.value; return editor.value?.can().undo() || false; }); const canRedo = computed(() => { tick.value; return editor.value?.can().redo() || false; });
let normalizeNextGalleryUpdate = false;
const normalizeGalleryMarkdown = (markdown) => markdown.replace(/(^|\n)(!\[[^\n]*\]\([^\n]*\))\n\n(?=!\[)/g, '$1$2\n');
const publish = (markdown) => { const value = normalizeNextGalleryUpdate ? normalizeGalleryMarkdown(markdown) : markdown; normalizeNextGalleryUpdate = false; sourceValue.value = value; lastValue.value = value; if (value !== props.modelValue) emit('update:modelValue', value); };
const activeBlock = computed(() => { tick.value; if (sourceMode.value) return 'paragraph'; for (const level of [2, 3, 4]) if (editor.value?.isActive('heading', { level })) return `heading-${level}`; return 'paragraph'; });
const sourceRange = () => ({ start: sourceInput.value?.selectionStart ?? sourceValue.value.length, end: sourceInput.value?.selectionEnd ?? sourceValue.value.length });
const replaceSourceRange = (start, end, replacement, selectionStart = start + replacement.length, selectionEnd = selectionStart) => { publish(`${sourceValue.value.slice(0, start)}${replacement}${sourceValue.value.slice(end)}`); nextTick(() => { sourceInput.value?.focus(); sourceInput.value?.setSelectionRange(selectionStart, selectionEnd); }); };
const wrapSourceSelection = (before, after, placeholder) => { const { start, end } = sourceRange(); const selected = sourceValue.value.slice(start, end) || placeholder; replaceSourceRange(start, end, `${before}${selected}${after}`, start + before.length, start + before.length + selected.length); };
const prefixSourceLines = (prefixForLine, stripHeading = false) => { const { start, end } = sourceRange(); const lineStart = sourceValue.value.lastIndexOf('\n', Math.max(0, start - 1)) + 1; const nextBreak = sourceValue.value.indexOf('\n', end); const lineEnd = nextBreak === -1 ? sourceValue.value.length : nextBreak; const lines = sourceValue.value.slice(lineStart, lineEnd).split('\n').map((line, index) => `${prefixForLine(index)}${stripHeading ? line.replace(/^#{1,6}\s+/, '') : line}`); replaceSourceRange(lineStart, lineEnd, lines.join('\n'), lineStart, lineStart + lines.join('\n').length); };
const insertSourceBlock = (block) => { const { start, end } = sourceRange(); const before = start > 0 && sourceValue.value[start - 1] !== '\n' ? '\n\n' : ''; const after = end < sourceValue.value.length && sourceValue.value[end] !== '\n' ? '\n\n' : '\n'; replaceSourceRange(start, end, `${before}${block}${after}`); };
const refresh = () => { tick.value += 1; }; const active = (name, attrs) => { tick.value; return sourceMode.value ? false : (editor.value?.isActive(name, attrs) || false); }; const command = (name) => { if (!editable.value) return; if (sourceMode.value) { if (name === 'toggleBulletList') prefixSourceLines(() => '- '); else if (name === 'toggleOrderedList') prefixSourceLines((index) => `${index + 1}. `); else if (name === 'toggleBlockquote') prefixSourceLines(() => '> '); return; } const chain = editor.value?.chain().focus(); if (chain && typeof chain[name] === 'function') chain[name]().run(); };
const closeTable = () => { if (tableMenu.value) tableMenu.value.open = false; }; const tableCommand = (name) => { command(name); closeTable(); }; const insertTable = () => { if (!editable.value) return; if (sourceMode.value) insertSourceBlock('| Column 1 | Column 2 | Column 3 |\n| --- | --- | --- |\n|  |  |  |\n|  |  |  |'); else editor.value?.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run(); closeTable(); }; const toggleMark = (name) => { if (!editable.value) return; if (sourceMode.value) { const marks = { bold: ['**', '**', tr('bold text', '粗体文字')], italic: ['_', '_', tr('italic text', '斜体文字')], strike: ['~~', '~~', tr('struck text', '删除文字')], code: ['`', '`', tr('code', '代码')] }; const mark = marks[name]; if (mark) wrapSourceSelection(...mark); return; } command(`toggle${name[0].toUpperCase()}${name.slice(1)}`); };
const setBlock = (event) => { if (!editable.value) return; if (sourceMode.value) { const value = event.target.value; prefixSourceLines(() => value === 'paragraph' ? '' : `${'#'.repeat(Number(value.split('-')[1]))} `, true); return; } const chain = editor.value?.chain().focus(); if (!chain) return; event.target.value === 'paragraph' ? chain.setParagraph().run() : chain.setHeading({ level: Number(event.target.value.split('-')[1]) }).run(); };
const closeLink = () => { linkOpen.value = false; sourceLinkSelection.value = null; }; const editLink = () => { if (!editor.value || !editable.value) return; sourceLinkSelection.value = sourceMode.value ? sourceRange() : null; linkDraft.value = sourceMode.value ? '' : (editor.value.getAttributes('link').href || ''); linkOpen.value = true; nextTick(() => { linkInput.value?.focus(); linkInput.value?.select(); }); }; const applyLink = () => { if (!editor.value || !editable.value) return; if (sourceMode.value) { const range = sourceLinkSelection.value || sourceRange(); const selected = sourceValue.value.slice(range.start, range.end) || tr('link text', '链接文字'); const replacement = linkDraft.value.trim() ? `[${selected}](${linkDraft.value.trim()})` : selected; replaceSourceRange(range.start, range.end, replacement); closeLink(); return; } const chain = editor.value.chain().focus().extendMarkRange('link'); linkDraft.value.trim() ? chain.setLink({ href: linkDraft.value.trim() }).run() : chain.unsetLink().run(); closeLink(); }; const removeLink = () => { linkDraft.value = ''; applyLink(); };
const toggleSource = () => { if (!editor.value) return; if (!sourceMode.value) { sourceValue.value = editor.value.getMarkdown(); sourceMode.value = true; return; } if (requiresSourceMode(sourceValue.value)) { emit('warning', tr('Remove unsupported Markdown features before switching to visual editing.', '请先移除当前不支持的 Markdown 语法，再切换到可视化编辑。')); return; } editor.value.commands.setContent(sourceValue.value || '', { contentType: 'markdown', emitUpdate: false }); sourceMode.value = false; refresh(); editor.value.commands.focus(); };
const uploadButtonText = computed(() => uploadStatus.value?.progress >= 95 ? tr('Processing...', '处理中...') : tr('Uploading... {progress}%', '上传中... {progress}%', { progress: uploadStatus.value?.progress || 0 })); const uploadStatusText = computed(() => uploadStatus.value?.status === 'uploading' ? `${uploadStatus.value.progress}%` : uploadStatus.value?.status === 'success' ? tr('Complete', '完成') : uploadStatus.value?.status === 'cancelled' ? tr('Cancelled', '已取消') : tr('Failed', '失败'));
const validateImage = (file) => { const types = new Set(props.imageAccept.split(',').map((v) => v.trim())); if (!types.has(file.type) && !/\.(png|jpe?g|gif|webp|svg)$/i.test(file.name || '')) return tr('Unsupported image format.', '不支持该图片格式。'); if (file.size > props.maxImageSize) return tr('File exceeds the size limit.', '图片超过大小限制。'); return ''; };
const progress = (value, file) => { const data = typeof value === 'number' ? { percentage: value } : (value || {}); const ratio = Number(data.total) > 0 ? (Number(data.loaded) / Number(data.total)) * 100 : 0; const percentage = data.percentage ?? data.progress ?? ratio; uploadStatus.value = { name: data.name || data.file?.name || file?.name || tr('Images', '图片'), progress: Math.max(0, Math.min(100, Number(percentage) || 0)), status: data.status || 'uploading', error: '' }; };
const insertImages = (images) => { if (sourceMode.value) { const markdown = images.map(({ url, alt, title }) => `![${String(alt || 'image').replace(/\]/g, '\\]')}](${url}${title ? ` "${String(title).replace(/"/g, '\\"')}"` : ''})`).join('\n\n'); if (markdown) insertSourceBlock(markdown); return; } const nodes = images.flatMap(({ url, alt, title }) => [{ type: 'image', attrs: { src: url, alt: alt || 'image', title: title || null } }, { type: 'paragraph' }]); if (nodes.length) editor.value?.chain().focus().insertContent(nodes).run(); };
const applyImageDescription = () => { if (!selectedImage.value || !editable.value) return; editor.value?.chain().focus().updateAttributes('image', { alt: imageAltDraft.value.trim() || 'image' }).run(); refresh(); };
const newGalleryItem = () => ({ id: `gallery-${++gallerySequence.value}`, url: '', alt: '', title: '', caption: '' });
const openGallery = () => { if (!editable.value || !props.enableGallery) return; galleryError.value = ''; galleryPickerId.value = null; galleryItems.value = [newGalleryItem(), newGalleryItem()]; galleryOpen.value = true; };
const closeGallery = () => { if (!galleryUploading.value) { galleryOpen.value = false; galleryPickerId.value = null; galleryError.value = ''; } };
const setGalleryColumns = (count) => { while (galleryItems.value.length < count) galleryItems.value.push(newGalleryItem()); while (galleryItems.value.length > count) galleryItems.value.pop(); };
const removeGalleryItem = (index) => { if (galleryItems.value.length <= 2) return; galleryItems.value.splice(index, 1); };
const moveGalleryItem = (index, delta) => { const next = index + delta; if (next < 0 || next >= galleryItems.value.length) return; const values = galleryItems.value.slice(); [values[index], values[next]] = [values[next], values[index]]; galleryItems.value = values; };
const pickGalleryImage = (itemId) => { galleryPickerId.value = itemId; emit('gallery-pick-image', { itemId, onSelect: selectGalleryImage }); };
const selectGalleryImage = (asset) => { const item = galleryItems.value.find((entry) => entry.id === galleryPickerId.value); if (!item || !asset?.url) return; Object.assign(item, { url: asset.url, alt: asset.alt || item.alt, title: asset.title || item.title }); galleryPickerId.value = null; galleryError.value = ''; };
const closeGalleryPicker = () => { galleryPickerId.value = null; };
const openGalleryUpload = (itemId) => { galleryUploadTarget.value = itemId; galleryFileInput.value?.click(); };
const handleGalleryUpload = async (event) => { const file = event.target.files?.[0]; event.target.value = ''; const target = galleryUploadTarget.value; galleryUploadTarget.value = null; if (!file || !target || !props.uploadImages) return; const message = validateImage(file); if (message) { galleryError.value = message; return; } galleryUploading.value = true; galleryError.value = ''; const controller = new AbortController(); try { const result = await props.uploadImages([file], { signal: controller.signal, onProgress: () => {}, file }); const asset = Array.isArray(result) ? result.find((entry) => entry?.url) : null; if (!asset) throw new Error(tr('The upload returned no image URL.', '上传结果中没有可用的图片地址。')); selectGalleryImageFor(target, asset); } catch (error) { galleryError.value = error?.message || String(error); } finally { galleryUploading.value = false; } };
const selectGalleryImageFor = (itemId, asset) => { const item = galleryItems.value.find((entry) => entry.id === itemId); if (item && asset?.url) Object.assign(item, { url: asset.url, alt: asset.alt || item.alt, title: asset.title || item.title }); };
const insertGallery = () => { if (!canInsertGallery.value || !editable.value) return; try { const markdown = buildGalleryMarkdown(galleryItems.value); if (sourceMode.value) insertSourceBlock(markdown); else { const instance = editor.value; if (!instance) return; const imageNodes = galleryItems.value.map(({ url, alt, title, caption }) => instance.schema.nodes.image.create({ src: String(url).trim(), alt: String(caption || alt || 'image').trim(), title: title ? String(title).trim() : null })); const content = instance.schema.nodes.doc.create(null, imageNodes).content; normalizeNextGalleryUpdate = true; const inserted = instance.commands.insertContentAt(instance.state.selection, content); if (!inserted) { normalizeNextGalleryUpdate = false; throw new Error('The gallery could not be inserted at the current selection.'); } instance.commands.focus(); } closeGallery(); } catch (error) { normalizeNextGalleryUpdate = false; galleryError.value = error?.message || String(error); } };
const cancelUpload = () => { const controller = uploadController.value; if (!controller || controller.signal.aborted) return; controller.abort(); uploadStatus.value = { name: uploadStatus.value?.name || tr('Images', '图片'), progress: uploadStatus.value?.progress || 0, status: 'cancelled', error: '' }; emit('upload-cancel', uploadingFiles.value); };
const uploadFiles = async (files) => { if (!files.length || !props.uploadImages || !editable.value || uploading.value) return; const validFiles = []; for (const file of files) { const message = validateImage(file); if (message) { const error = new Error(message); uploadStatus.value = { name: file.name, progress: 0, status: 'error', error: message }; emit('upload-error', error); } else validFiles.push(file); } if (!validFiles.length) return; const controller = new AbortController(); uploadController.value = controller; uploadingFiles.value = validFiles; const onProgress = (value) => { if (!controller.signal.aborted) progress(value, validFiles[0]); }; onProgress.signal = controller.signal; onProgress.onProgress = onProgress; progress(0, validFiles[0]); try { const result = await props.uploadImages(validFiles, onProgress); if (controller.signal.aborted) throw new DOMException('Image upload was cancelled.', 'AbortError'); const images = Array.isArray(result) ? result.filter((item) => item?.url) : []; if (!images.length) throw new Error(tr('The upload returned no image URLs.', '上传结果中没有可用的图片地址。')); insertImages(images); uploadStatus.value = { name: tr('{count} images', '{count} 张图片', { count: images.length }), progress: 100, status: 'success', error: '' }; emit('upload-complete', images); } catch (error) { if (controller.signal.aborted || error?.name === 'AbortError') { uploadStatus.value = { name: uploadStatus.value?.name || validFiles[0].name, progress: uploadStatus.value?.progress || 0, status: 'cancelled', error: '' }; } else { uploadStatus.value = { name: uploadStatus.value?.name || validFiles[0].name, progress: uploadStatus.value?.progress || 0, status: 'error', error: error?.message || String(error) }; emit('upload-error', error); } } finally { if (uploadController.value === controller) uploadController.value = null; uploadingFiles.value = []; } };
const handleUpload = async (event) => { const files = Array.from(event.target.files || []); event.target.value = ''; await uploadFiles(files); }; const handleEditorFiles = (files) => { const images = Array.from(files || []).filter((file) => file.type?.startsWith('image/') || /\.(png|jpe?g|gif|webp|svg)$/i.test(file.name || '')); if (!images.length || !props.uploadImages || !editable.value || uploading.value) return false; void uploadFiles(images); return true; };
const remotePastePayload = (clipboardData) => { if (!clipboardData) return null; const candidates = [['markdown', clipboardData.getData?.('text/markdown')], ['markdown', clipboardData.getData?.('text/plain')], ['html', clipboardData.getData?.('text/html')]]; for (const [format, content] of candidates) { if (content && findRemoteImageReferences(content, { format }).length) return { content, format }; } return null; };
const handleRemotePaste = (event, insert) => { if (!props.importRemoteImages || !editable.value || remoteImportController.value) return false; const payload = remotePastePayload(event.clipboardData); if (!payload) return false; const references = findRemoteImageReferences(payload.content, { format: payload.format }); const controller = new AbortController(); const report = () => {}; Object.assign(report, { signal: controller.signal, onProgress: report }); remoteImportController.value = controller; event.preventDefault(); emit('remote-image-import-start', references); void importRemoteImagesFromContent(payload.content, props.importRemoteImages, report, { format: payload.format }).then((result) => { if (controller.signal.aborted) return; insert(result.content, payload.format); emit('remote-image-import-complete', result); }).catch((error) => { if (controller.signal.aborted) return; insert(payload.content, payload.format); emit('remote-image-import-error', { error, references, content: payload.content }); }).finally(() => { if (remoteImportController.value === controller) remoteImportController.value = null; }); return true; };
const handleSourcePaste = (event) => { if (handleEditorFiles(event.clipboardData?.files)) { event.preventDefault(); return; } const { start, end } = sourceRange(); handleRemotePaste(event, (content) => replaceSourceRange(start, end, content)); };
const selectImageOnMouseDown = (view, event) => { const target = event.target; if (target?.tagName !== 'IMG' || !view.editable) return false; const position = view.posAtDOM(target, 0); if (view.state.doc.nodeAt(position)?.type.name !== 'image') return false; view.dispatch(view.state.tr.setSelection(NodeSelection.create(view.state.doc, position))); view.focus(); event.preventDefault(); return true; };
const outside = (event) => { if (tableMenu.value?.open && !tableMenu.value.contains(event.target)) closeTable(); if (linkOpen.value && !linkPanel.value?.contains(event.target)) closeLink(); };
watch(selectedImage, (value) => { imageAltDraft.value = value?.alt || ''; });
watch(() => props.modelValue, (value) => { if (value !== lastValue.value) sourceValue.value = value || ''; if (!editor.value || value === lastValue.value) return; if (props.autoSourceMode && requiresSourceMode(value)) { sourceMode.value = true; return; } if (!sourceMode.value) editor.value.commands.setContent(value || '', { contentType: 'markdown', emitUpdate: false }); refresh(); });
watch(editable, (value) => editor.value?.setEditable(value));
onMounted(() => { document.addEventListener('pointerdown', outside); try { sourceMode.value = props.autoSourceMode && requiresSourceMode(props.modelValue); editor.value = new Editor({ editable: editable.value, enableInputRules: true, extensions: [StarterKit.configure({ heading: { levels: [1, 2, 3, 4, 5, 6] } }), Image.configure({ allowBase64: props.allowBase64Images }), TableKit, Placeholder.configure({ placeholder: props.placeholder || tr('Start writing...', '开始输入正文…') }), Markdown], content: props.modelValue || '', contentType: 'markdown', editorProps: { attributes: { class: 'nono-rich-editor__prosemirror', 'aria-label': props.placeholder || tr('Rich text editor', '富文本编辑器') }, handleDOMEvents: { mousedown: selectImageOnMouseDown }, handlePaste: (view, event) => { if (handleEditorFiles(event.clipboardData?.files)) return true; const range = { from: view.state.selection.from, to: view.state.selection.to }; return handleRemotePaste(event, (content, format) => editor.value?.commands.insertContentAt(range, content, { contentType: format })); }, handleDrop: (_view, event) => handleEditorFiles(event.dataTransfer?.files) }, onUpdate: ({ editor: instance }) => { publish(instance.getMarkdown()); refresh(); }, onSelectionUpdate: refresh, onFocus: () => { focused.value = true; }, onBlur: () => { focused.value = false; } }); if (props.autofocus && !props.disabled) nextTick(() => editor.value?.commands.focus()); } catch (error) { editorError.value = tr('The rich text editor could not start.', '富文本编辑器未能启动。'); console.error('Failed to initialize editor', error); } });
onBeforeUnmount(() => { uploadController.value?.abort(); remoteImportController.value?.abort(); document.removeEventListener('pointerdown', outside); editor.value?.destroy(); editor.value = null; });
</script>
